config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'kibis#index'
  resources :kibis
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kibi.rb
class Kibi < ApplicationRecord
  validates :description, presence: true, length: { maximum: 140, minimum: 1 }
  validates :name, presence: true, length: { maximum: 50, minimum: 1 }
  validates :address, presence: true, length: { maximum: 50, minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kibis_controller.rb
class KibisController < ApplicationController

  def index
    @kibi = Kibi.last
  end

  def new
    @kibi = Kibi.new
  end

  def create
    @kibi = Kibi.create(kibi_params)
    if @kibi.invalid?
      flash[:error] = '<strong> you didnt complete all fields!!</strong>'
    end
    redirect_to root_path
  end

  private

  def kibi_params
    params.require(:kibi).permit(:name, :description, :address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kibis_helper.rb
module KibisHelper
end

app/views/kibis/index.html.erb
<br /><br /><br />

<h1 class="experimental-kibi">QUIZ 1: PIPELINE SET UP</h1>
<br /><br /><br />
<h2 class="subheader">This app just wants to get to know you!</h2>

<br />

<p class="desc">It's just to prove that I can set up the pipeline required for a web app</p>
<br /><br /><br />

<div class="experimental-kibi">
  The last person to submit their workplace was:
  <div class="desc">
    <%= Kibi.last.name %> 
  </div>

  <br />
  And they work at:
  <div class="subheader">
    <%= Kibi.last.description %>  
  </div>
</div>

app/views/kibis/new.html.erb
<br />
<h1 class="experimental-kibi">Care to tell me who you are and where you work?</h1>

<div class="subheader col-8 offset-2">
  <%= simple_form_for @kibi do |f| %>
    <%= f.input :name, label: 'Your name please' %>
    <%= f.input :description, label: 'Name of your workplace please' %>
    <%= f.input :address, label: 'Actual work address please' %>
    <%= f.submit 'Send it!!' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raquibbi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="row">
      <div class="col-3">
        <%= link_to 'HOME', root_path %>
      </div>
      <div class="col-4">
        All Quizzes are here!! 
      </div>
      <div class="col-5">
        <%= link_to 'Quiz #2', new_kibi_path %>
        <%= link_to 'Quiz #3', '#' %>
      </div>
    </header>

    <%= yield %>
  </body>
</html>